### ISSUE TITLE
Error on running line 169 (TaskClassifST)

### ISSUE THREAD

**Issue by njambi-r** [konstantinschellenberg/EO-College_Slangbos#1]
https://github.com/konstantinschellenberg/EO-College_Slangbos/blob/0894c896f698ce3ee10e89d460df766b02ab4848/R/01_modelling.R#L169

Hi,

First off, thanks for the tutorial.

I keep getting the following error on running line 169: 

Error in .__Task__initialize(self = self, private = private, super = super,  : 
  Assertion on 'feature types' failed: Must be a subset of {'logical','integer','numeric','character','factor','ordered','POSIXct'}, but is {'integer','sfc_POINT','numeric','factor'}.

I am using the dataset provided in the course. I even tried re-installing R version 4.1.2 but the error persists.

Any insights on what could be causing this?

**Comment by konstantinschellenberg** [comment]
Hi nhambi-r,

thanks for posting this issue! I was out of office lately, thus I could not response to your inquiry here - I'm sorry.

The error arises from changes in the API of the mlr³ sub-package `mlr3spatiotempcv` > 1.0.1 (most recent is 2.0.1, see [here](https://mlr3spatiotempcv.mlr-org.com/news/index.html))

The problem can be shifted around when installing the spatial backend lib `mlr3spatiotempcv` from github via `remotes::install_github("mlr-org/mlr3spatiotempcv")` (it is Version 2.0.1.9000 then) since the bug apparently only exists in the CRAN version.

I've posted an issue to the package dev team - you can follow the discussion [here](https://github.com/mlr-org/mlr3spatiotempcv/issues/206).

Thanks for following my tutorial and keep my updated on any other comments or issues.

Best,
konstantinschellenberg
